
# Diccionario de Identificadores de Aplicación GS1 (AI) y sus significados, formatos
GS1_AIs = {
    '00': 'Código de Contenedor de Envío Serial (SSCC-18)',
    '01': 'Número Global de Artículo Comercial (GTIN-14)',
    '02': 'GTIN de Artículos Comerciales en una Unidad Logística',
    '10': 'Número de Lote o Batch (Longitud Variable)',
    '11': 'Fecha de Producción (AA/MM/DD)',
    '12': 'Fecha de Vencimiento (AA/MM/DD)',
    '13': 'Fecha de Embalaje (AA/MM/DD)',
    '15': 'Fecha de Consumo Preferente (AA/MM/DD)',
    '17': 'Fecha de Caducidad (AA/MM/DD)',
    '20': 'Variante Interna del Producto',
    '21': 'Número de Serie (Longitud Variable)',
    '22': 'Cantidad HIBCC, Fecha, Lote y Enlace',
    '240': 'Identificación Adicional del Producto (Longitud Variable)',
    '241': 'Número de Parte del Cliente (Longitud Variable)',
    '242': 'Número de Variación de Pedido a Medida (Longitud Variable)',
    '243': 'Número de Componente de Embalaje (Longitud Variable)',
    '250': 'Número de Serie Secundario (Longitud Variable)',
    '251': 'Referencia a la Entidad de Origen (Longitud Variable)',
    '253': 'Identificador Global de Tipo de Documento (Longitud Variable)',
    '254': 'Componente de Extensión GLN (Longitud Variable)',
    '255': 'Número Global de Cupón',
    '30': 'Cantidad Variable',
    '310x': 'Peso Neto (Kilogramos) - 6 dígitos, punto decimal variable',
    '311x': 'Longitud (Metros) - 6 dígitos, punto decimal variable',
    '312x': 'Ancho/Diámetro (Metros) - 6 dígitos, punto decimal variable',
    '313x': 'Profundidad/Grosor (Metros) - 6 dígitos, punto decimal variable',
    '314x': 'Área (Metros Cuadrados) - 6 dígitos, punto decimal variable',
    '315x': 'Volumen (Litros) - 6 dígitos, punto decimal variable',
    '316x': 'Volumen (Metros Cúbicos) - 6 dígitos, punto decimal variable',
    '320x': 'Peso Neto (Libras) - 6 dígitos, punto decimal variable',
    '321x': 'Longitud (Pulgadas) - 6 dígitos, punto decimal variable',
    '322x': 'Longitud (Pies) - 6 dígitos, punto decimal variable',
    '323x': 'Longitud (Yardas) - 6 dígitos, punto decimal variable',
    '324x': 'Ancho/Diámetro (Pulgadas) - 6 dígitos, punto decimal variable',
    '325x': 'Ancho/Diámetro (Pies) - 6 dígitos, punto decimal variable',
    '326x': 'Ancho/Diámetro (Yardas) - 6 dígitos, punto decimal variable',
    '327x': 'Profundidad/Grosor (Pulgadas) - 6 dígitos, punto decimal variable',
    '328x': 'Profundidad/Grosor (Pies) - 6 dígitos, punto decimal variable',
    '329x': 'Profundidad/Grosor (Yardas) - 6 dígitos, punto decimal variable',
    '330x': 'Peso Bruto del Contenedor (Kilogramos) - 6 dígitos, punto decimal variable',
    '331x': 'Longitud del Contenedor (Metros) - 6 dígitos, punto decimal variable',
    '332x': 'Ancho del Contenedor (Metros) - 6 dígitos, punto decimal variable',
    '333x': 'Profundidad del Contenedor (Metros) - 6 dígitos, punto decimal variable',
    '334x': 'Área del Contenedor (Metros Cuadrados) - 6 dígitos, punto decimal variable',
    '335x': 'Volumen Bruto del Contenedor (Litros) - 6 dígitos, punto decimal variable',
    '336x': 'Volumen Bruto del Contenedor (Metros Cúbicos) - 6 dígitos, punto decimal variable',
    '337x': 'Kilogramos por Metro Cuadrado - 6 dígitos, punto decimal variable',
    '390x': 'Cantidad a Pagar (6 dígitos, punto decimal variable)',
    '391x': 'Cantidad a Pagar - Área Monetaria Única',
    '392x': 'Cantidad a Pagar (Longitud Variable)',
    '393x': 'Cantidad a Pagar con Código de Moneda ISO',
    '400': 'Número de Pedido (Longitud Variable)',
    '401': 'GINC (Número Global de Identificación para Envío)',
    '402': 'GSIN (Número Global de Identificación de Envío)',
    '403': 'Código de Ruta',
    '410': 'Enviar A Número Global de Ubicación (GLN)',
    '411': 'Facturar A Número Global de Ubicación (GLN)',
    '412': 'Comprado de GLN',
    '413': 'Enviar Para o Entregar A GLN',
    '414': 'Ubicación GLN',
    '415': 'Número Global de Ubicación de la Parte Facturadora',
    '416': 'GLN de Ubicación de Producción o Servicio',
    '420': 'Código Postal de Envío',
    '421': 'Código Postal de Envío con Código de País',
    '422': 'País de Origen de un Artículo Comercial',
    '423': 'Reglas Empresariales Específicas del País',
    '4300': 'Información de Contacto de Envío',
    '4326': 'Información de Contacto de Facturación'
}

# Mapeo de rangos de prefijos GS1 a países
# GS1_PREFIX_COUNTRIES - Mapeo de prefijos GS1 a países
GS1_PREFIX_COUNTRIES = {
    '000-019': 'Estados Unidos',
    '020-029': 'Números de Circulación Restringida dentro de una región geográfica',
    '030-039': 'Estados Unidos',
    '040-049': 'Números de Circulación Restringida dentro de una empresa',
    '050-059': 'GS1 US (Reservado para uso futuro)',
    '060-139': 'Estados Unidos',
    '200-299': 'Números de Circulación Restringida dentro de una región geográfica',
    '300-379': 'Francia y Mónaco',
    '380': 'Bulgaria',
    '383': 'Eslovenia',
    '385': 'Croacia',
    '387': 'Bosnia y Herzegovina',
    '389': 'Montenegro',
    '390': 'Kosovo',
    '400-440': 'Alemania',
    '450-459': 'Japón',
    '460-469': 'Rusia',
    '470': 'Kirguistán',
    '471': 'Taiwán',
    '474': 'Estonia',
    '475': 'Letonia',
    '476': 'Azerbaiyán',
    '477': 'Lituania',
    '478': 'Uzbekistán',
    '479': 'Sri Lanka',
    '480': 'Filipinas',
    '481': 'Bielorrusia',
    '482': 'Ucrania',
    '483': 'Turkmenistán',
    '484': 'Moldavia',
    '485': 'Armenia',
    '486': 'Georgia',
    '487': 'Kazajistán',
    '488': 'Tayikistán',
    '489': 'Hong Kong',
    '490-499': 'Japón',
    '500-509': 'Reino Unido',
    '520-521': 'Grecia',
    '528': 'Líbano',
    '529': 'Chipre',
    '530': 'Albania',
    '531': 'Macedonia del Norte',
    '535': 'Malta',
    '539': 'Irlanda',
    '540-549': 'Bélgica y Luxemburgo',
    '560': 'Portugal',
    '569': 'Islandia',
    '570-579': 'Dinamarca, Islas Feroe, Groenlandia',
    '590': 'Polonia',
    '594': 'Rumania',
    '599': 'Hungría',
    '600-601': 'Sudáfrica',
    '603': 'Ghana',
    '604': 'Senegal',
    '608': 'Baréin',
    '609': 'Mauricio',
    '611': 'Marruecos',
    '613': 'Argelia',
    '615': 'Nigeria',
    '616': 'Kenia',
    '617': 'Camerún',
    '618': 'Costa de Marfil',
    '619': 'Túnez',
    '620': 'Tanzania',
    '621': 'Siria',
    '622': 'Egipto',
    '623': 'Brunéi',
    '624': 'Libia',
    '625': 'Jordania',
    '626': 'Irán',
    '627': 'Kuwait',
    '628': 'Arabia Saudita',
    '629': 'Emiratos Árabes Unidos',
    '640-649': 'Finlandia',
    '690-699': 'China',
    '700-709': 'Noruega',
    '729': 'Israel',
    '730-739': 'Suecia',
    '740': 'Guatemala',
    '741': 'El Salvador',
    '742': 'Honduras',
    '743': 'Nicaragua',
    '744': 'Costa Rica',
    '745': 'Panamá',
    '746': 'República Dominicana',
    '750': 'México',
    '754-755': 'Canadá',
    '759': 'Venezuela',
    '760-769': 'Suiza y Liechtenstein',
    '770-771': 'Colombia',
    '773': 'Uruguay',
    '775': 'Perú',
    '777': 'Bolivia',
    '778-779': 'Argentina',
    '780': 'Chile',
    '784': 'Paraguay',
    '786': 'Ecuador',
    '789-790': 'Brasil',
    '800-839': 'Italia, San Marino, Ciudad del Vaticano',
    '840-849': 'España y Andorra',
    '850': 'Cuba',
    '858': 'Eslovaquia',
    '859': 'República Checa',
    '860': 'Serbia',
    '865': 'Mongolia',
    '867': 'Corea del Norte',
    '868-869': 'Turquía',
    '870-879': 'Países Bajos',
    '880': 'Corea del Sur',
    '883': 'Myanmar',
    '884': 'Camboya',
    '885': 'Tailandia',
    '888': 'Singapur',
    '890': 'India',
    '893': 'Vietnam',
    '896': 'Pakistán',
    '899': 'Indonesia',
    '900-919': 'Austria',
    '930-939': 'Australia',
    '940-949': 'Nueva Zelanda',
    '950': 'Oficina Global de GS1: Aplicaciones Especiales',
    '955': 'Malasia',
    '958': 'Macao',
    '960-969': 'Oficina Global - Asignaciones GTIN-8',
    '977': 'Publicaciones en Serie (ISSN)',
    '978-979': 'Bookland (ISBN)',
    '980': 'Recibos de Reembolso',
    '981-983': 'Identificación de Cupones GS1 para Áreas Monetarias Comunes',
    '990-999': 'Identificación de Cupones GS1'
}
