# Dictionary of GS1 Application Identifiers (AI) and their meanings, formats
GS1_AIs = {
    '00': 'Serial Shipping Container Code (SSCC-18)',
    '01': 'Global Trade Item Number (GTIN-14)',
    '02': 'GTIN of Trade Items in a Logistic Unit',
    '10': 'Batch or Lot Number (Variable Length)',
    '11': 'Production Date (YYMMDD)',
    '12': 'Due Date (YYMMDD)',
    '13': 'Packaging Date (YYMMDD)',
    '15': 'Best Before Date (YYMMDD)',
    '17': 'Expiration Date (YYMMDD)',
    '20': 'Internal Product Variant',
    '21': 'Serial Number (Variable Length)',
    '22': 'HIBCC Quantity, Date, Batch and Link',
    '240': 'Additional Product Identification (Variable Length)',
    '241': 'Customer Part Number (Variable Length)',
    '242': 'Made-to-Order Variation Number (Variable Length)',
    '243': 'Packaging Component Number (Variable Length)',
    '250': 'Secondary Serial Number (Variable Length)',
    '251': 'Reference to Source Entity (Variable Length)',
    '253': 'Global Document Type Identifier (Variable Length)',
    '254': 'GLN Extension Component (Variable Length)',
    '255': 'Global Coupon Number',
    '30': 'Variable Quantity',
    '310x': 'Net Weight (Kilograms) - 6 digits, variable decimal place',
    '311x': 'Length (Meters) - 6 digits, variable decimal place',
    '312x': 'Width/Diameter (Meters) - 6 digits, variable decimal place',
    '313x': 'Depth/Thickness (Meters) - 6 digits, variable decimal place',
    '314x': 'Area (Square Meters) - 6 digits, variable decimal place',
    '315x': 'Volume (Liters) - 6 digits, variable decimal place',
    '316x': 'Volume (Cubic Meters) - 6 digits, variable decimal place',
    '320x': 'Net Weight (Pounds) - 6 digits, variable decimal place',
    '321x': 'Length (Inches) - 6 digits, variable decimal place',
    '322x': 'Length (Feet) - 6 digits, variable decimal place',
    '323x': 'Length (Yards) - 6 digits, variable decimal place',
    '324x': 'Width/Diameter (Inches) - 6 digits, variable decimal place',
    '325x': 'Width/Diameter (Feet) - 6 digits, variable decimal place',
    '326x': 'Width/Diameter (Yards) - 6 digits, variable decimal place',
    '327x': 'Depth/Thickness (Inches) - 6 digits, variable decimal place',
    '328x': 'Depth/Thickness (Feet) - 6 digits, variable decimal place',
    '329x': 'Depth/Thickness (Yards) - 6 digits, variable decimal place',
    '330x': 'Container Gross Weight (Kilograms) - 6 digits, variable decimal place',
    '331x': 'Container Length (Meters) - 6 digits, variable decimal place',
    '332x': 'Container Width (Meters) - 6 digits, variable decimal place',
    '333x': 'Container Depth (Meters) - 6 digits, variable decimal place',
    '334x': 'Container Area (Square Meters) - 6 digits, variable decimal place',
    '335x': 'Container Gross Volume (Liters) - 6 digits, variable decimal place',
    '336x': 'Container Gross Volume (Cubic Meters) - 6 digits, variable decimal place',
    '337x': 'Kilogram Per Square Meter - 6 digits, variable decimal place',
    '390x': 'Amount Payable (6 digits, variable decimal place)',
    '391x': 'Amount Payable - Single Monetary Area',
    '392x': 'Amount Payable (Variable Length)',
    '393x': 'Amount Payable with ISO Currency Code',
    '400': 'Order Number (Variable Length)',
    '401': 'GINC (Global Identification Number for Consignment)',
    '402': 'GSIN (Global Shipment Identification Number)',
    '403': 'Routing Code',
    '410': 'Ship To Global Location Number (GLN)',
    '411': 'Bill To Global Location Number (GLN)',
    '412': 'Purchased From GLN',
    '413': 'Ship For or Deliver To GLN',
    '414': 'Location GLN',
    '415': 'Global Location Number of the Invoicing Party',
    '416': 'GLN of Production or Service Location',
    '420': 'Ship To Postal Code',
    '421': 'Ship To Postal Code with Country Code',
    '422': 'Country of Origin of a Trade Item',
    '423': 'Country Specific Business Rules',
    '4300': 'Ship To Contact Information',
    '4326': 'Bill To Contact Information'
}


# Mapping of GS1 prefix ranges to countries
# GS1_PREFIX_COUNTRIES - Mapped GS1 prefixes to countries
GS1_PREFIX_COUNTRIES = {
    '000-019': 'United States',
    '020-029': 'Restricted Circulation Numbers within a geographic region',
    '030-039': 'United States',
    '040-049': 'Restricted Circulation Numbers within a company',
    '050-059': 'GS1 US (Reserved for future use)',
    '060-139': 'United States',
    '200-299': 'Restricted Circulation Numbers within a geographic region',
    '300-379': 'France & Monaco',
    '380': 'Bulgaria',
    '383': 'Slovenia',
    '385': 'Croatia',
    '387': 'Bosnia & Herzegovina',
    '389': 'Montenegro',
    '390': 'Kosovo',
    '400-440': 'Germany',
    '450-459': 'Japan',
    '460-469': 'Russia',
    '470': 'Kyrgyzstan',
    '471': 'Taiwan',
    '474': 'Estonia',
    '475': 'Latvia',
    '476': 'Azerbaijan',
    '477': 'Lithuania',
    '478': 'Uzbekistan',
    '479': 'Sri Lanka',
    '480': 'Philippines',
    '481': 'Belarus',
    '482': 'Ukraine',
    '483': 'Turkmenistan',
    '484': 'Moldova',
    '485': 'Armenia',
    '486': 'Georgia',
    '487': 'Kazakhstan',
    '488': 'Tajikistan',
    '489': 'Hong Kong',
    '490-499': 'Japan',
    '500-509': 'United Kingdom',
    '520-521': 'Greece',
    '528': 'Lebanon',
    '529': 'Cyprus',
    '530': 'Albania',
    '531': 'North Macedonia',
    '535': 'Malta',
    '539': 'Ireland',
    '540-549': 'Belgium & Luxembourg',
    '560': 'Portugal',
    '569': 'Iceland',
    '570-579': 'Denmark, Faroe Islands, Greenland',
    '590': 'Poland',
    '594': 'Romania',
    '599': 'Hungary',
    '600-601': 'South Africa',
    '603': 'Ghana',
    '604': 'Senegal',
    '608': 'Bahrain',
    '609': 'Mauritius',
    '611': 'Morocco',
    '613': 'Algeria',
    '615': 'Nigeria',
    '616': 'Kenya',
    '617': 'Cameroon',
    '618': 'Ivory Coast',
    '619': 'Tunisia',
    '620': 'Tanzania',
    '621': 'Syria',
    '622': 'Egypt',
    '623': 'Brunei',
    '624': 'Libya',
    '625': 'Jordan',
    '626': 'Iran',
    '627': 'Kuwait',
    '628': 'Saudi Arabia',
    '629': 'United Arab Emirates',
    '640-649': 'Finland',
    '690-699': 'China',
    '700-709': 'Norway',
    '729': 'Israel',
    '730-739': 'Sweden',
    '740': 'Guatemala',
    '741': 'El Salvador',
    '742': 'Honduras',
    '743': 'Nicaragua',
    '744': 'Costa Rica',
    '745': 'Panama',
    '746': 'Dominican Republic',
    '750': 'Mexico',
    '754-755': 'Canada',
    '759': 'Venezuela',
    '760-769': 'Switzerland & Liechtenstein',
    '770-771': 'Colombia',
    '773': 'Uruguay',
    '775': 'Peru',
    '777': 'Bolivia',
    '778-779': 'Argentina',
    '780': 'Chile',
    '784': 'Paraguay',
    '786': 'Ecuador',
    '789-790': 'Brazil',
    '800-839': 'Italy, San Marino, Vatican City',
    '840-849': 'Spain & Andorra',
    '850': 'Cuba',
    '858': 'Slovakia',
    '859': 'Czech Republic',
    '860': 'Serbia',
    '865': 'Mongolia',
    '867': 'North Korea',
    '868-869': 'Turkey',
    '870-879': 'Netherlands',
    '880': 'South Korea',
    '883': 'Myanmar',
    '884': 'Cambodia',
    '885': 'Thailand',
    '888': 'Singapore',
    '890': 'India',
    '893': 'Vietnam',
    '896': 'Pakistan',
    '899': 'Indonesia',
    '900-919': 'Austria',
    '930-939': 'Australia',
    '940-949': 'New Zealand',
    '950': 'GS1 Global Office: Special applications',
    '955': 'Malaysia',
    '958': 'Macau',
    '960-969': 'Global Office - GTIN-8 allocations',
    '977': 'Serial Publications (ISSN)',
    '978-979': 'Bookland (ISBN)',
    '980': 'Refund receipts',
    '981-983': 'GS1 coupon identification for common currency areas',
    '990-999': 'GS1 coupon identification'
}
